name: hrc-net
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch>=2.1
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - numpy
  - scipy
  - pyyaml
  - tqdm
  - h5py
  - scikit-learn
  - pip:
      - einops
